### ISSUE TITLE
vnet modules not compatible with version 2.x

### ISSUE THREAD

**Issue by avamkrb** [ned1313/Implementing-Terraform-on-Microsoft-Azure#2]
In the Module 1 to create the vnet I needed to add 

version             =  "~> 1.2.0"

to the vnet-main module as it was erroring  with: 

Error: Unsupported argument

  on main.tf line 45, in module "vnet-main":
  45:   location            = var.location

An argument named "location" is not expected here.

It looks live version 2 doesnt require several of the provided variables.

**Comment by mdlister** [comment]
I get the same error, according to the usage from https://registry.terraform.io/modules/Azure/network/azurerm/3.1.1 the Resource Group and location are defined outside of the module.

**Comment by mdlister** [comment]
> variable "vnet_cidr_range" {
  type    = list
  default = ["10.0.0.0/16"]
}
fixes one of the issues

**Comment by ned1313** [comment]
I have set the version of the module in the exercise files to 1.2.0. Eventual to do is update all to version 2.0 of the module and version 2.0 of the AzureRM provider.
